<a href="https://colab.research.google.com/github/Lijazilla/Numpy_Pandas_lessons/blob/main/creating_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
arr = np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.random.rand()

0.7482455535820952

In [13]:
np.random.rand(4)

array([0.84157056, 0.83021852, 0.82635769, 0.25277007])

In [16]:
np.random.rand(4,4)

array([[0.6647271 , 0.44658605, 0.36922683, 0.90490449],
       [0.82205952, 0.05870435, 0.27430974, 0.53505043],
       [0.47851486, 0.8360614 , 0.68909055, 0.61051599],
       [0.05531792, 0.15696119, 0.12115862, 0.80882971]])

In [17]:
np.random.randint(1,15)

4

In [18]:
np.random.randint(1,100,(10,10))

array([[30, 98, 58, 40, 68, 73, 59, 45, 68, 86],
       [49, 58, 66, 79, 36, 37, 66, 72, 19,  5],
       [47, 76, 14, 93, 45, 53, 33, 87, 47, 65],
       [41, 86, 59, 55, 84, 64, 52, 48, 90,  5],
       [66, 89,  6, 67, 73, 56, 15, 10, 72, 70],
       [63, 30, 68, 10, 33, 11, 55, 14, 77, 96],
       [57, 39, 75,  2, 22, 19, 79, 62, 28, 43],
       [79,  4, 81, 97, 28, 65, 99, 14, 18, 71],
       [51, 39, 38, 53, 98, 51, 85, 86, 24, 86],
       [11, 95, 12, 84, 13, 63, 90, 73,  5, 26]])