<a href="https://colab.research.google.com/github/Lijazilla/Numpy_Pandas_lessons/blob/main/Numpy_shape_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
arr = np.random.randint(1,10,(3,2))
arr

array([[8, 5],
       [3, 9],
       [5, 4]])

In [5]:
arr.shape

(3, 2)

In [6]:
arr

array([[8, 5],
       [3, 9],
       [5, 4]])

In [7]:
arr.reshape(1,6)

array([[8, 5, 3, 9, 5, 4]])

In [9]:
arr.reshape(2,3)

array([[8, 5, 3],
       [9, 5, 4]])

In [11]:
np.reshape(arr,(1,6))

array([[8, 5, 3, 9, 5, 4]])

In [13]:
np.reshape(arr,(2,3), 'C')

array([[8, 5, 3],
       [9, 5, 4]])

In [14]:
np.reshape(arr,(2,3), 'F')

array([[8, 5, 9],
       [3, 5, 4]])

In [15]:
np.reshape(arr,(2,3), 'A')

array([[8, 5, 3],
       [9, 5, 4]])

In [25]:
array = np.arange(0,15)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
array.ndim

1

In [30]:
array.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
array = np.expand_dims(np.array(array, ndmin=4), axis=1)

In [49]:
array

array([[[[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]]]])