<a href="https://colab.research.google.com/github/Lijazilla/Numpy_Pandas_lessons/blob/main/numpy_data_type.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [11]:
arr = np.array([1,2,3,4], dtype='float64')
arr.dtype

dtype('float64')

In [8]:
arr

array([1., 2., 3., 4.])

In [15]:
arr = arr.astype(np.float64)
arr

array([1., 2., 3., 4.])

In [17]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [18]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [21]:
arr = np.array(['0','1','2','3','4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

In [22]:
single = np.csingle(arr)
single

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j], dtype=complex64)

In [24]:
long_v1 = np.half(arr)
long_v1

array([0., 1., 2., 3., 4.], dtype=float16)

In [25]:
double = np.clongdouble(arr)
double

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j], dtype=complex256)