<a href="https://colab.research.google.com/github/Lijazilla/Numpy_Pandas_lessons/blob/main/numpy_copy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
trozo_arr= arr[0:6]
trozo_arr

array([0, 1, 2, 3, 4, 5])

In [10]:
trozo_arr[:] = 0
trozo_arr

array([0, 0, 0, 0, 0, 0])

In [11]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [16]:
arr_copy = arr.copy()

In [18]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [19]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [20]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])