<a href="https://colab.research.google.com/github/Lijazilla/Numpy_Pandas_lessons/blob/main/Numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
arr = np.array(lista)

In [6]:
type(arr)

numpy.ndarray

In [8]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[1] + arr[7]

10

In [13]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
matriz[0,2]

3

In [19]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr[0:3]

array([1, 2, 3])

In [23]:
arr[::3]

array([1, 4, 7])

In [29]:
arr[-1]

9

In [28]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])