<a href="https://colab.research.google.com/github/Lijazilla/Numpy_Pandas_lessons/blob/main/numpy_dimentions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [7]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [12]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9],[40,45,3]],[[1,2,3],[4,5,6],[7,8,9],[40,45,3]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [40 45  3]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [40 45  3]]]


3

##Agregar o eliminar dimensiones

In [14]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [21]:
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [22]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


In [23]:
tensor = np.array([1,2,3])
tensor

array([1, 2, 3])

In [29]:
tensor_2 = np.expand_dims(np.array([1,2,3], ndmin=4), axis=0)
tensor_2

array([[[[[1, 2, 3]]]]])

In [30]:
tensor_3 = np.squeeze(tensor_2)
tensor_3

array([1, 2, 3])